# Makefile for multiplayer-fabric-llm NIF.
# Mirrors the GPU/CPU backend support matrix from turboquant-godot modules/llm/SCsub.
#
# Supported backends (auto-detected):
#   Metal   — macOS, iOS     (GGML_USE_METAL)
#   Vulkan  — macOS, Linux, Windows, Android  (GGML_USE_VULKAN, requires VULKAN_SDK)
#   CPU     — all platforms  (GGML_USE_CPU, ARM or x86 SIMD)

PRIV_DIR := priv
NIF_SO   := $(PRIV_DIR)/llm_nif.so
TP       := thirdparty/llama_cpp

UNAME    := $(shell uname -s)
ARCH     := $(shell uname -m)

# ── Erlang include paths ──────────────────────────────────────────────────────
ERL_ROOT  := $(shell erl -eval 'io:format("~s",[code:root_dir()])' -s init stop -noshell 2>/dev/null)
ERTS_ROOT := $(shell erl -eval 'io:format("~s",[code:lib_dir(erts)])' -s init stop -noshell 2>/dev/null)
ERL_INC   := $(ERL_ROOT)/usr/include
ERTS_INC  := $(ERTS_ROOT)/include

# ── Include paths (matches SCsub all_inc) ────────────────────────────────────
INCS := \
  -I$(ERL_INC) -I$(ERTS_INC) \
  -I$(TP)/ggml/include \
  -I$(TP)/ggml/src \
  -I$(TP)/ggml/src/ggml-cpu \
  -I$(TP)/include \
  -I$(TP)/src \
  -I$(TP)/common \
  -I$(TP)/vendor \
  -Ic_src

# ── Common defines (matches SCsub env_tp CPPDEFINES) ─────────────────────────
DEFINES := \
  -DGGML_USE_LLAMAFILE=0 \
  -DLLAMA_BUILD \
  -DGGML_USE_CPU \
  -DGGML_VERSION=\"0.10.0\" \
  -DGGML_COMMIT=\"turboquant-kv-cache\"

# ── Base compiler flags ───────────────────────────────────────────────────────
# -w suppresses vendored-code warnings (matches SCsub env_tp.Append(CCFLAGS=["-w"]))
# -include errno.h matches SCsub
CCFLAGS_BASE  := -O2 -march=native -fPIC -w -include errno.h $(INCS) $(DEFINES)
CFLAGS        := $(CCFLAGS_BASE)
# -fexceptions + forced includes match SCsub env_tp CXXFLAGS
CXXFLAGS      := $(CCFLAGS_BASE) -std=c++17 -fexceptions \
                 -include memory -include c_src/llama_compat.h
LDFLAGS       := -shared

# ── Platform detection ────────────────────────────────────────────────────────
IS_MACOS   := $(filter Darwin, $(UNAME))
IS_LINUX   := $(filter Linux,  $(UNAME))
IS_ARM     := $(filter arm64 aarch64 armv7, $(ARCH))

# ── Metal backend (macOS) ─────────────────────────────────────────────────────
METAL_SRCS :=
ifeq ($(IS_MACOS), Darwin)
  DEFINES  += -DGGML_USE_METAL -DGGML_METAL_EMBED_LIBRARY
  LDFLAGS  += -framework Metal -framework Foundation -framework CoreGraphics
  METAL_DIR = $(TP)/ggml/src/ggml-metal

  METAL_CPP_SRCS := \
    $(METAL_DIR)/ggml-metal.cpp \
    $(METAL_DIR)/ggml-metal-ops.cpp \
    $(METAL_DIR)/ggml-metal-common.cpp

  # ggml-metal-device.cpp and .m both needed — different object names
  METAL_DEVICE_CPP_OBJ := $(METAL_DIR)/ggml-metal-device-cxx.o
  METAL_CONTEXT_M_OBJ  := $(METAL_DIR)/ggml-metal-context-objc.o
  METAL_DEVICE_M_OBJ   := $(METAL_DIR)/ggml-metal-device-objc.o

  # Embed Metal shader at build time (runtime MTLNewLibraryWithSource — no xcrun needed)
  METAL_EMBED_GEN := $(METAL_DIR)/ggml-metal-embed.gen.cpp

  METAL_EXTRA_OBJS := \
    $(METAL_DEVICE_CPP_OBJ) \
    $(METAL_CONTEXT_M_OBJ) \
    $(METAL_DEVICE_M_OBJ)

  METAL_SRCS := $(METAL_CPP_SRCS) $(METAL_EMBED_GEN)
endif

# ── Vulkan backend (optional — needs VULKAN_SDK) ──────────────────────────────
VK_SRCS :=
VK_SHADER_CPPS :=
ifdef VULKAN_SDK
  DEFINES  += -DGGML_USE_VULKAN
  VK_DIR    = $(TP)/ggml/src/ggml-vulkan
  INCS     += -I$(VK_DIR) -I$(VULKAN_SDK)/include
  LDFLAGS  += -L$(VULKAN_SDK)/lib -lvulkan
  VK_SRCS   = $(VK_DIR)/ggml-vulkan.cpp
  # Precompiled shader .cpp files (generated by glslc — run `make shaders` first)
  VK_SHADER_CPPS := $(wildcard $(VK_DIR)/vulkan-shaders.spv/*.comp.cpp)
  ifeq ($(IS_MACOS), Darwin)
    LDFLAGS += -rpath $(VULKAN_SDK)/lib
  endif
endif

# ── CPU arch-specific sources (matches SCsub _is_arm logic) ──────────────────
CPU_ARCH_SRCS :=
ifeq ($(IS_ARM), )
  # x86: quants.c + all .cpp in arch/x86/
  CPU_ARCH_SRCS += $(TP)/ggml/src/ggml-cpu/arch/x86/quants.c
  CPU_ARCH_SRCS += $(wildcard $(TP)/ggml/src/ggml-cpu/arch/x86/*.cpp)
else
  # ARM (Apple Silicon, Android arm64)
  CPU_ARCH_SRCS += \
    $(TP)/ggml/src/ggml-cpu/arch/arm/quants.c \
    $(TP)/ggml/src/ggml-cpu/arch/arm/repack.cpp \
    $(TP)/ggml/src/ggml-cpu/arch/arm/cpu-feats.cpp
endif

# ── Source lists (exact mirrors of SCsub lists) ───────────────────────────────

GGML_C_SRCS := \
  $(TP)/ggml/src/ggml.c \
  $(TP)/ggml/src/ggml-alloc.c \
  $(TP)/ggml/src/ggml-quants.c \
  $(TP)/ggml/src/ggml-turbo-quant.c

GGML_CPP_SRCS := \
  $(TP)/ggml/src/ggml-backend.cpp \
  $(TP)/ggml/src/ggml-backend-reg.cpp \
  $(TP)/ggml/src/ggml-backend-meta.cpp \
  $(TP)/ggml/src/ggml-backend-dl.cpp \
  $(TP)/ggml/src/ggml-threading.cpp \
  $(TP)/ggml/src/ggml-opt.cpp \
  $(TP)/ggml/src/gguf.cpp

# Explicit CPU sources (no ggml-cpu.c/.cpp — handled below with collision avoidance)
GGML_CPU_SRCS := \
  $(TP)/ggml/src/ggml-cpu/binary-ops.cpp \
  $(TP)/ggml/src/ggml-cpu/hbm.cpp \
  $(TP)/ggml/src/ggml-cpu/ops.cpp \
  $(TP)/ggml/src/ggml-cpu/quants.c \
  $(TP)/ggml/src/ggml-cpu/repack.cpp \
  $(TP)/ggml/src/ggml-cpu/traits.cpp \
  $(TP)/ggml/src/ggml-cpu/unary-ops.cpp \
  $(TP)/ggml/src/ggml-cpu/vec.cpp \
  $(CPU_ARCH_SRCS)

# ggml-cpu collision: both .c AND .cpp needed — explicit unique object names
GGML_CPU_C_OBJ   := $(TP)/ggml/src/ggml-cpu/ggml-cpu-c.o
GGML_CPU_CXX_OBJ := $(TP)/ggml/src/ggml-cpu/ggml-cpu-cxx.o

LLAMA_SRCS := \
  $(wildcard $(TP)/src/models/*.cpp) \
  $(TP)/src/llama.cpp \
  $(TP)/src/llama-adapter.cpp \
  $(TP)/src/llama-arch.cpp \
  $(TP)/src/llama-batch.cpp \
  $(TP)/src/llama-chat.cpp \
  $(TP)/src/llama-context.cpp \
  $(TP)/src/llama-cparams.cpp \
  $(TP)/src/llama-grammar.cpp \
  $(TP)/src/llama-graph.cpp \
  $(TP)/src/llama-hparams.cpp \
  $(TP)/src/llama-impl.cpp \
  $(TP)/src/llama-io.cpp \
  $(TP)/src/llama-kv-cache.cpp \
  $(TP)/src/llama-kv-cache-iswa.cpp \
  $(TP)/src/llama-memory.cpp \
  $(TP)/src/llama-memory-hybrid.cpp \
  $(TP)/src/llama-memory-hybrid-iswa.cpp \
  $(TP)/src/llama-memory-recurrent.cpp \
  $(TP)/src/llama-mmap.cpp \
  $(TP)/src/llama-model.cpp \
  $(TP)/src/llama-model-loader.cpp \
  $(TP)/src/llama-model-saver.cpp \
  $(TP)/src/llama-quant.cpp \
  $(TP)/src/llama-sampler.cpp \
  $(TP)/src/llama-vocab.cpp \
  $(TP)/src/unicode.cpp \
  $(TP)/src/unicode-data.cpp

COMMON_SRCS := \
  $(TP)/common/common.cpp \
  $(TP)/common/chat.cpp \
  $(TP)/common/sampling.cpp \
  $(TP)/common/log.cpp

NIF_SRC := c_src/llm_nif.c

# ── Object file lists ─────────────────────────────────────────────────────────
C_OBJS   := $(GGML_C_SRCS:.c=.o) \
             $(filter %.o, $(patsubst %.c,%.o,$(filter %.c,$(GGML_CPU_SRCS)))) \
             $(filter %.o, $(patsubst %.c,%.o,$(filter %.c,$(CPU_ARCH_SRCS))))

CXX_OBJS := $(GGML_CPP_SRCS:.cpp=.o) \
             $(filter %.o, $(patsubst %.cpp,%.o,$(filter %.cpp,$(GGML_CPU_SRCS)))) \
             $(filter %.o, $(patsubst %.cpp,%.o,$(filter %.cpp,$(CPU_ARCH_SRCS)))) \
             $(LLAMA_SRCS:.cpp=.o) \
             $(COMMON_SRCS:.cpp=.o) \
             $(METAL_SRCS:.cpp=.o) \
             $(VK_SRCS:.cpp=.o) \
             $(VK_SHADER_CPPS:.cpp=.o)

EXPLICIT_OBJS := \
  $(GGML_CPU_C_OBJ) \
  $(GGML_CPU_CXX_OBJ) \
  $(METAL_EXTRA_OBJS)

NIF_OBJ := c_src/llm_nif.o

ALL_OBJS := $(C_OBJS) $(CXX_OBJS) $(EXPLICIT_OBJS) $(NIF_OBJ)

# ── Rules ─────────────────────────────────────────────────────────────────────
.PHONY: all clean shaders

all: $(PRIV_DIR) $(NIF_SO)

$(PRIV_DIR):
	mkdir -p $(PRIV_DIR)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Collision: ggml-cpu.c → unique object
$(GGML_CPU_C_OBJ): $(TP)/ggml/src/ggml-cpu/ggml-cpu.c
	$(CC) $(CFLAGS) -c $< -o $@

# Collision: ggml-cpu.cpp → unique object
$(GGML_CPU_CXX_OBJ): $(TP)/ggml/src/ggml-cpu/ggml-cpu.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

ifeq ($(IS_MACOS), Darwin)
# Metal shader embed: cat shader sources into a C char array
$(METAL_EMBED_GEN): $(METAL_DIR)/ggml-metal.metal $(TP)/ggml/src/ggml-common.h $(METAL_DIR)/ggml-metal-impl.h
	python3 c_src/gen_metal_embed.py $@ $^

# Collision: ggml-metal-device.cpp → unique object
$(METAL_DEVICE_CPP_OBJ): $(METAL_DIR)/ggml-metal-device.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Objective-C: -fno-objc-arc (matches SCsub env_objc)
$(METAL_CONTEXT_M_OBJ): $(METAL_DIR)/ggml-metal-context.m
	$(CC) $(CFLAGS) -fno-objc-arc -c $< -o $@

$(METAL_DEVICE_M_OBJ): $(METAL_DIR)/ggml-metal-device.m
	$(CC) $(CFLAGS) -fno-objc-arc -c $< -o $@
endif

c_src/llm_nif.o: c_src/llm_nif.c
	$(CC) $(CFLAGS) -c $< -o $@

$(NIF_SO): $(ALL_OBJS)
	$(CXX) $(LDFLAGS) -o $@ $^

clean:
	find $(TP) -name "*.o" -delete
	rm -f c_src/*.o $(NIF_SO) $(METAL_EMBED_GEN) 2>/dev/null || true
