# SPDX-License-Identifier: MIT
# Copyright (c) 2026-present K. S. Ernest (iFire) Lee

defmodule Mix.Tasks.GenMetalEmbed do
  @shortdoc "Embed Metal shader source as a C char array for ggml-metal-embed.gen.cpp"

  @moduledoc """
  Generates `ggml-metal-embed.gen.cpp` by embedding the Metal shader source
  as a C string literal. Matches the `metal_builders.py generate_metal_embed`
  pattern from turboquant-godot.

  Called by the Makefile when building on macOS:

      $(MAKE) -C .. gen_metal_embed OUTPUT=... METAL=... HEADERS=...

  Or directly:

      mix gen_metal_embed OUTPUT=path/to/embed.gen.cpp METAL=path/to/ggml-metal.metal
  """

  use Mix.Task

  @impl Mix.Task
  def run(args) do
    opts = parse_args(args)

    output = opts[:output] || Mix.raise("OUTPUT= required")
    metal  = opts[:metal]  || Mix.raise("METAL= required")

    src = File.read!(metal)

    lines =
      src
      |> String.split("\n")
      |> Enum.map_join("", fn line ->
        escaped = line |> String.replace("\\", "\\\\") |> String.replace("\"", "\\\"") |> String.replace("\t", "\\t")
        "        \"#{escaped}\\n\"\n"
      end)

    content = """
    // Auto-generated by mix gen_metal_embed — do not edit.
    #include "ggml-metal.h"

    const char * ggml_metal_get_library_source(void) {
        static const char src[] =
    #{lines}        "";
        return src;
    }
    """

    File.mkdir_p!(Path.dirname(output))
    File.write!(output, content)
    Mix.shell().info("Generated #{output}")
  end

  defp parse_args(args) do
    Enum.reduce(args, %{}, fn arg, acc ->
      case String.split(arg, "=", parts: 2) do
        [k, v] -> Map.put(acc, String.downcase(k) |> String.to_atom(), v)
        _ -> acc
      end
    end)
  end
end
